import { User } from "./user";

export const USERS: User[] = [
	{
		id: 1,
		intra: "mmuster",
		firstname: "Max",
		lastname: "Mustermann",
		username: "MusterDude",
		email: "mmuster@mock.com",
		picture: "../../assets/cage.jpeg",
		twoFAEnabled: true,
		twoFAsecret: "i like big butts",
		status: "online",
		wins: 12,
		losses: 23,
		xp: 223,
		rank: 1,
		map: 2,
		achievements: [1, 3, 5]
	},
	{
		id: 2,
		intra: "jdoe",
		firstname: "Jon",
		lastname: "Doe",
		username: "JonDude",
		email: "jdoe@mock.com",
		picture: "../../assets/cage.jpeg",
		twoFAEnabled: false,
		status: "offline",
		wins: 1,
		losses: 12,
		xp: 2,
		rank: 3,
		map: 1,
		achievements: []
	},
	{
		id: 3,
		intra: "jbiden",
		firstname: "Joe",
		lastname: "Biden",
		username: "BigJoe",
		email: "jbiden@mock.com",
		picture: "../assets/biden.jpeg",
		twoFAEnabled: true,
		twoFAsecret: "i stole the election",
		status: "gaming",
		wins: 600,
		losses: 120,
		xp: 4374,
		rank: 2,
		map: 3,
		achievements: [4, 5],
		hasUnreadMessagesToActiveUser: true
	},
	{
		id: 4,
		intra: "dtrump",
		firstname: "Donald",
		lastname: "Trump",
		username: "TheRealD",
		email: "dtrump@mock.com",
		picture: "../assets/trump.jpeg",
		twoFAEnabled: false,
		status: "offline",
		wins: 1,
		losses: 120,
		xp: 1,
		rank: 4,
		map: 3,
		achievements: [1, 4],
		hasUnreadMessagesToActiveUser: false,
	},
	{
		id: 5,
		intra: "smischni",
		firstname: "Saskia",
		lastname: "Mischnick",
		username: "smischni",
		email: "smischni@student.42wolfsburg.de",
		picture: "../assets/profile.jpg",
		twoFAEnabled: true,
		twoFAsecret: "I love Vinny more",
		status: "online",
		wins: 15,
		losses: 12,
		xp: 178,
		rank: 5,
		map: 1,
		achievements: [3, 6],
		hasUnreadMessagesToActiveUser: true
	},
	{
		id: 6,
		intra: "jsubel",
		firstname: "Jonas",
		lastname: "Subel",
		username: "jsubel",
		email: "jsubel@student.42wolfsburg.de",
		picture: "../assets/profile.jpg",
		twoFAEnabled: false,
		status: "online",
		wins: 12,
		losses: 15,
		xp: 174,
		rank: 6,
		map: 1,
		achievements: [2, 3],
		hasUnreadMessagesToActiveUser: false
	},
	{
		id: 7,
		intra: "tjairus",
		firstname: "Triinu",
		lastname: "Jairus",
		username: "tjairus",
		email: "tjairus@student.42wolfsburg.de",
		picture: "../assets/profile.jpg",
		twoFAEnabled: false,
		status: "gaming",
		wins: 15,
		losses: 12,
		xp: 178,
		rank: 7,
		map: 3,
		achievements: [1, 6],
		hasUnreadMessagesToActiveUser: true
	},
	{
		id: 8,
		intra: "fmollenh",
		firstname: "Ferenc",
		lastname: "Mollenhauer",
		username: "fmollenh",
		email: "fmollenh@student.42wolfsburg.de",
		picture: "../assets/profile.jpg",
		twoFAEnabled: false,
		status: "online",
		wins: 15,
		losses: 12,
		xp: 178,
		rank: 8,
		map: 2,
		achievements: [4, 5, 6],
		hasUnreadMessagesToActiveUser: false
	},
	{
		id: 9,
		intra: "fsemke",
		firstname: "Florian",
		lastname: "Semke",
		username: "fsemke",
		email: "fsemke@student.42wolfsburg.de",
		picture: "../assets/profile.jpg",
		twoFAEnabled: false,
		status: "offline",
		wins: 15,
		losses: 12,
		xp: 178,
		rank: 9,
		map: 2,
		achievements: [1, 3, 4],
		hasUnreadMessagesToActiveUser: true
	},
];