import { User } from "./objects/user";

export const USERS: User[] = [
	// this is an empty user that can be used to see if findUser functions work
	{
		id: -1,
		intra: '',
		firstname: '',
		lastname: '',
		username: '',
		email: '',
		picture: '',
		twoFAEnabled: false,
		twoFAsecret: '',
		status: '',
		wins: 0,
		losses: 0,
		xp: 0,
		rank: 0,
		map: 0,
		isLoggedIn: false
	},
	{
		id: 1,
		intra: "mmuster",
		firstname: "Max",
		lastname: "Mustermann",
		username: "MusterDude",
		email: "mmuster@mock.com",
		picture: "../../assets/cage.jpeg",
		twoFAEnabled: true,
		twoFAsecret: "i like big butts",
		status: "online",
		wins: 12,
		losses: 23,
		xp: 223,
		rank: 1,
		map: 2,
		isLoggedIn: true
	},
	{
		id: 2,
		intra: "jdoe",
		firstname: "Jon",
		lastname: "Doe",
		username: "JonDude",
		email: "jdoe@mock.com",
		picture: "../../assets/cage.jpeg",
		twoFAEnabled: false,
		twoFAsecret: undefined,
		status: "offline",
		wins: 1,
		losses: 12,
		xp: 2,
		rank: 3,
		map: 1,
		isLoggedIn: true
	},
	{
		id: 3,
		intra: "jbiden",
		firstname: "Joe",
		lastname: "Biden",
		username: "BigJoe",
		email: "jbiden@mock.com",
		picture: "../assets/biden.jpeg",
		twoFAEnabled: true,
		twoFAsecret: "i stole the election",
		status: "online",
		wins: 600,
		losses: 120,
		xp: 4374,
		rank: 2,
		map: 3,
		isLoggedIn: false
	},
	{
		id: 4,
		intra: "dtrump",
		firstname: "Donald",
		lastname: "Trump",
		username: "TheRealD",
		email: "dtrump@mock.com",
		picture: "../assets/trump.jpeg",
		twoFAEnabled: false,
		twoFAsecret: undefined,
		status: "online",
		wins: 1,
		losses: 120,
		xp: 1,
		rank: 4,
		map: 3,
		isLoggedIn: true
	}
];