version: '3.8'

# for prod and eval, we need to clean this up

services:

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ${PWD}/frontend:/app
    ports:
      - 80:80
    restart: unless-stopped
    container_name: frontend
    networks:
      - nw_app

  backend:
    build:
      context: ./backend
    networks:
      - nw_database
      - nw_app
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env
    restart: unless-stopped
    container_name: backend

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: postgresql_database
    networks:
      - nw_database
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: postgresql_database

networks:
  nw_database:
    driver: bridge
  nw_app:
    driver: bridge

volumes:
  postgres-data:
