version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    # depends_on: ['backend']
    ports:
      - 80:80
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    networks:
      - nw_database
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ${PWD}/backend:/app
    restart: always
    container_name: backend

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: postgresql_database
    networks:
      - nw_database
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    container_name: postgresql_database

networks:
  nw_database:
    driver: bridge

volumes:
  postgres-data: