version: '3.8'


services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - DOMAIN=${DOMAIN}
    depends_on:
      - backend
    ports:
      - 80:80
    restart: unless-stopped
    container_name: frontend
    networks:
      - nw_app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - database
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads/profile_pictures
    restart: unless-stopped
    container_name: backend
    networks:
      - nw_database
      - nw_app

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: postgresql_database
    networks:
      - nw_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: postgresql_database

networks:
  nw_database:
    driver: bridge
  nw_app:
    driver: bridge

volumes:
  postgres-data:
  uploads:

