version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    # depends_on: ['backend']
    ports:
      - 80:80
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    networks:
      - nw_database
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    environment:
      - PGUSER=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres_dbw
    networks:
      - nw_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    container_name: postgresql_database

networks:
  nw_database:
    driver: bridge

volumes:
  postgres-data: